### ISSUE TITLE
Horizontal Orientation

### ISSUE THREAD

**Issue by sinnott-balin** [gizmosachin/ColorSlider#11]
First off this is an excellent module, great work.  

I have been playing around with the Sketchpad example and can't seem to get the horizontal orientation to function properly.  I have tried editing the default orientation, as well as the drawLayer inside commonInit(), but the color slider always appears vertical.  

![simulator screen shot feb 26 2017 2 31 34 pm](https://cloud.githubusercontent.com/assets/14949170/23344392/9211edea-fc49-11e6-95c0-232c911fb1f8.png)

**Comment by gizmosachin** [comment]
Hi Balin - thanks so much!

`ColorSlider` won't change its own frame to be wider than it is tall when you set the `orientation` to `.horizontal` – you still have to explicitly set the frame. Since the frame in the example is set to have a width of 12 and height of 150, the slider showed up like it did in your screenshot.

I tried modifying `ViewController.swift` in the Example project by setting the orientation to `.horizontal` in `commonInit` and then swapping the width and height in `viewDidLayoutSubviews`:
```swift
let colorSliderWidth = CGFloat(150)
let colorSliderHeight = CGFloat(12)
```

The result correctly displays a horizontal slider control:

![simulator screen shot feb 26 2017 11 18 22 pm](https://cloud.githubusercontent.com/assets/193174/23352123/34fd4682-fc7a-11e6-9605-90d606f05522.png)
