### ISSUE TITLE
Carthage build failed

### ISSUE THREAD

**Issue by olivanov** [gizmosachin/ColorSlider#25]
Hi and thanks for the great work!

When I'm trying to build the project with Carthage, I have the following error:

/Carthage/Checkouts/ColorSlider/Sources/GradientView.swift:241:23: error: use of undeclared type 'Gradient'
fileprivate extension Gradient {
                      ^~~~~~~~

I'm using Xcode 9.2 / Swift 4

Cheers!

**Comment by gizmosachin** [comment]
Hey! Forgot to update the README when this was fixed in v4.0.1. You'll want to specify at least `4.0.1` (latest is `4.1`) in your Cartfile. I updated the README to reflect this. Thanks!

**Comment by olivanov** [comment]
Hi Sachin,

I did the update in my Cartfile with version > 4.1.1. However, I have exactly the same error when trying to build...

Could you please check again? 
Thanks!

**Comment by gizmosachin** [comment]
Yep! Will check this weekend.

**Comment by gizmosachin** [comment]
Hi @olivanov - looks like the build was broken because the `Gradient.swift` file was added in v4.1 but not to the framework project. This wasn't caught by CI because we were only using the Cocoapods linter, which automatically creates the Cocoapods project from all files in the `Sources` directory. 

I pushed `4.1.2` and verified it builds locally with Carthage. Travis will now also build the project with `xcodebuild` and also use the pod linter, so this doesn't happen again. Thanks!
